# Generated by Django 2.2 on 2023-05-26 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earphone_filters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='earphone',
            name='image',
            field=models.ImageField(default='path/to/default/image.jpg', upload_to='earphone_images'),
        ),
        migrations.AlterField(
            model_name='earphone',
            name='warranty_period',
            field=models.IntegerField(),
        ),
    ]
